# Generated by Django 6.0.2 on 2026-03-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
