# Generated by Django 6.0.2 on 2026-03-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_source_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='linked_questions',
            field=models.ManyToManyField(blank=True, related_name='incoming_node_links_via_content', to='core.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='linked_nodes',
            field=models.ManyToManyField(blank=True, related_name='incoming_question_links_via_content', to='core.node'),
        ),
        migrations.AddField(
            model_name='question',
            name='linked_questions',
            field=models.ManyToManyField(blank=True, related_name='incoming_question_links_via_content', to='core.question'),
        ),
    ]
