# Generated by Django 6.0.2 on 2026-03-04 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_node_linked_questions_question_linked_nodes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='linked_questions',
        ),
        migrations.AddField(
            model_name='node',
            name='source_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='source_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('node', 'Node'), ('question', 'Question')], default='node', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_questions', to='core.node'),
        ),
    ]
