# Generated by Django 6.0.2 on 2026-03-04 20:16

from django.db import migrations
import re

def migrate_questions_to_nodes(apps, schema_editor):
    Question = apps.get_model("core", "Question")
    Node = apps.get_model("core", "Node")
    Project = apps.get_model("core", "Project")
    
    default_project = Project.objects.first()
    if not default_project and Question.objects.exists():
        default_project = Project.objects.create(name="Default Migrated Project")
        
    old_to_new = {}
    
    # 1. Create new Nodes
    for q in Question.objects.all():
        q_proj = None
        
        curr_q = q
        while not q_proj and curr_q:
            if curr_q.source_node_id:
                src_node = Node.objects.filter(pk=curr_q.source_node_id).first()
                if src_node:
                    q_proj = src_node.project
                    break
            elif curr_q.source_question_id:
                curr_q = Question.objects.filter(pk=curr_q.source_question_id).first()
            else:
                break
                
        if not q_proj:
            q_proj = default_project
            
        # we can't do q.is_deleted directly if it's not present, but it's inherited so it's there
        new_node = Node.objects.create(
            title=q.title,
            content=q.answer,
            type="question",
            project=q_proj,
            source_text=q.source_text,
            is_deleted=q.is_deleted,
            created_at=q.created_at,
            updated_at=q.updated_at,
        )
        old_to_new[q.pk] = new_node.pk

    # 2. Update source_node for the newly created Nodes that were nested questions
    for q in Question.objects.all():
        new_node_pk = old_to_new.get(q.pk)
        new_node = Node.objects.get(pk=new_node_pk)
        
        if q.source_node_id:
            new_node.source_node_id = q.source_node_id
        elif q.source_question_id:
            new_node.source_node_id = old_to_new.get(q.source_question_id)
            
        new_node.save()
        
    # 3. Update Markdown Links in all Nodes
    for node in Node.objects.all():
        if not node.content:
            continue
            
        def repl(match):
            old_id = int(match.group(1))
            new_id = old_to_new.get(old_id, old_id)
            return f"](/api/question/{new_id}/detail)"
            
        new_content = re.sub(r'\]\(/api/question/(\d+)/detail\)', repl, node.content)
        if new_content != node.content:
            node.content = new_content
            node.save()
            
    # 4. Rebuild M2M Links for all nodes based on content
    node_pattern = r'\]\(/node/(\d+)/\)|\]\(/project/\d+/#node-(\d+)\)'
    q_pattern = r'\]\(/api/question/(\d+)/detail\)'
    for node in Node.objects.all():
        if not node.content:
            node.linked_nodes.clear()
            continue
            
        node_ids = set()
        for match in re.findall(node_pattern, node.content):
            for group in match:
                if group:
                    node_ids.add(int(group))
                    
        q_ids = set(int(pk) for pk in re.findall(q_pattern, node.content))
        all_ids = node_ids.union(q_ids)
        
        if node.pk in all_ids:
            all_ids.remove(node.pk)
            
        if all_ids:
            existing = list(Node.objects.filter(pk__in=all_ids).values_list('pk', flat=True))
            node.linked_nodes.set(existing)
        else:
            node.linked_nodes.clear()


def reverse_migrate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_node_linked_questions_node_source_node_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_questions_to_nodes, reverse_migrate)
    ]

