# Generated by Django 6.0.2 on 2026-03-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_data_migrate_questions_to_nodes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
